apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: azureappgw-ingress-res
  namespace: vote
spec:
  rules:
  - http:
      paths:
      - path: /vote(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 8080
      - path: /result(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: result
            port:
              number: 8081
