apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: result
  name: result
  namespace: vote
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: result
  type: ClusterIP
status:
  loadBalancer: {}
